# Generated by Django 4.2 on 2025-01-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterModelTable(
            name='gallery',
            table='Галерея',
        ),
    ]
